[build.environment]
  NODE_VERSION = "18"

  # Configuration for branch deploys for the branch named `staging`.
# Remember to replace `npm run build` with your site's build command 
# and replace `dist` with your site's publish directory.
[context.branch-deploy]
  command = "npm run build && cp ./custom-headers/_stagingHeaders ./.next/_headers"

[context.production]
  command = "npm run build && cp ./custom-headers/_productionHeaders ./.next/_headers"